// src/routes/attendance.js
const express = require('express');
const pool = require('../db');
const authenticateToken = require('../middleware/auth');
const zod = require('zod');
const jwt = require('jsonwebtoken'); // Import jsonwebtoken

const router = express.Router();

const attendanceSchema = zod.object({
  scannedQrToken: zod.string().min(1) // Now expects a token
});

// POST /attendance/mark - Mark attendance using a dynamic token
router.post('/mark', authenticateToken, async (req, res) => {
  const studentId = req.userId;
  if (req.userRole !== 'student') {
    return res.status(403).json({ message: 'Only students can mark attendance.' });
  }

  try {
    const { scannedQrToken } = attendanceSchema.parse(req.body);

    // 1. Verify and decode the JWT token
    let decodedToken;
    try {
      decodedToken = jwt.verify(scannedQrToken, process.env.JWT_SECRET);
    } catch (err) {
      return res.status(401).json({ message: 'Invalid or expired QR token.' });
    }

    const { facility_id: facilityId } = decodedToken;

    // 2. Validate the token against the database
    // This confirms the token was generated by your system and is currently valid
    const [sessionRows] = await pool.query(
      'SELECT id FROM qr_sessions WHERE qr_token = ? AND valid_until > NOW()',
      [scannedQrToken]
    );

    if (sessionRows.length === 0) {
      return res.status(403).json({ message: 'QR token is no longer active.' });
    }

    // 3. Perform the attendance cooldown check
    const [lastScanRows] = await pool.query(
      'SELECT scanned_at FROM attendance WHERE student_id = ? AND facility_id = ? ORDER BY scanned_at DESC LIMIT 1',
      [studentId, facilityId]
    );

    if (lastScanRows.length > 0) {
      const lastScannedAt = new Date(lastScanRows[0].scanned_at);
      const cooldownPeriod = 60 * 1000;
      if (Date.now() - lastScannedAt.getTime() < cooldownPeriod) {
        return res.status(409).json({ message: 'Duplicate scan attempt. Please wait a moment.' });
      }
    }

    // 4. Insert the new attendance record
    await pool.query(
      'INSERT INTO attendance (student_id, facility_id, scanned_at) VALUES (?, ?, NOW())',
      [studentId, facilityId]
    );

    res.status(201).json({ message: 'Attendance marked successfully.' });

  } catch (error) {
    if (error instanceof zod.ZodError) {
      return res.status(400).json({ errors: error.errors });
    }
    console.error('Attendance marking error:', error);
    res.status(500).json({ message: 'Server error.' });
  }
});

module.exports = router;